[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
zeta_testnet = "https://zetachain-evm.blockpi.network/v1/rpc/public"
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
polygon_amoy = "https://rpc-amoy.polygon.technology"

[etherscan]
zeta_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://zetachain.blockscout.com/api" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
polygon_amoy = { key = "${POLYGONSCAN_API_KEY}", url = "https://api-amoy.polygonscan.com/api" }
